/** @type {import('tailwindcss').Config} */
// Tokens mirror stitch_smart_forest_tracker/forest_management_system/DESIGN.md.
// DESIGN.md is the source of truth — update there first, then here.
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#f9f9ff',
        'surface-dim': '#cfdaf1',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eeff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fa',
        'on-surface': '#111c2c',
        'on-surface-variant': '#424844',
        'inverse-surface': '#263142',
        'inverse-on-surface': '#ebf1ff',
        outline: '#727973',
        'outline-variant': '#c2c8c2',
        'surface-tint': '#496455',
        primary: '#173124',
        'on-primary': '#ffffff',
        'primary-container': '#2d4739',
        'on-primary-container': '#98b5a3',
        'inverse-primary': '#b0cdbb',
        secondary: '#765840',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed5b6',
        'on-secondary-container': '#795b42',
        tertiary: '#4f1c00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#722c00',
        'on-tertiary-container': '#ff9159',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ccead6',
        'primary-fixed-dim': '#b0cdbb',
        'on-primary-fixed': '#062014',
        'on-primary-fixed-variant': '#324c3e',
        'secondary-fixed': '#ffdcc1',
        'secondary-fixed-dim': '#e6bfa1',
        'on-secondary-fixed': '#2b1704',
        'on-secondary-fixed-variant': '#5c412a',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-fixed-dim': '#ffb693',
        'on-tertiary-fixed': '#351000',
        'on-tertiary-fixed-variant': '#7a3000',
        background: '#f9f9ff',
        'on-background': '#111c2c',
        'surface-variant': '#d8e3fa',
        safety: '#FF6B00',
        'safety-hover': '#E66000',
      },
      fontFamily: {
        sans: ['"Public Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-main': '1.25rem',
        'gutter-grid': '1rem',
        'stack-sm': '0.5rem',
        'stack-md': '1rem',
        'stack-lg': '1.5rem',
        'touch-target': '3rem',
      },
    },
  },
  plugins: [],
};
